//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdsServiceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ads
    {
        public int AdID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public int UserID { get; set; }
        public int CityID { get; set; }
        public int CategoryID { get; set; }
        public int AdTypeID { get; set; }
        public int StatusID { get; set; }
        public string ad_image { get; set; }
    
        public virtual AdTypes AdTypes { get; set; }
        public virtual Categories Categories { get; set; }
        public virtual Cities Cities { get; set; }
        public virtual AdStatuses AdStatuses { get; set; }
        public virtual Users Users { get; set; }
    }
}
